### ISSUE TITLE
bug: Some error related to switching/opening buffers

### ISSUE THREAD

**Issue by IndianBoy42** [dccsillag/magma-nvim#10]
```
error caught in async handler '/home/amedhi/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/pyth
on3/magma.py:autocmd:BufUnload:* []'                                                                      
Traceback (most recent call last):                                                                        
  File "/home/amedhi/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py", line 47,
 in inner                                                                                                 
    func(self, *args, **kwargs)                                                                           
  File "/home/amedhi/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py", line 990
, in autocmd_bufunload                                                                                    
    magma = self.buffers.get(int(self.nvim.funcs.expand('<abuf>')))                                       
ValueError: invalid literal for int() with base 10: ''                        
```

I can't seem to nail down exactly when it happens but one reliable way is to hit `<leader>`, wait for which-key.nvim to show up then hit `<ESC>`

I see it is something to do with the BufUnload autocommand so I guess it's to do with leaving the buffer

Also doing a LSP search for references leads to this happening many times

**Comment by dccsillag** [comment]
I'll do a quick workaround for this, and then go looking. It looks like sometimes `BufUnload` is triggered with `<abuf>` being empty (which I thought wasn't supposed to happen?). This may actually be something I misunderstood from the documentation, or a bug in neovim.

**Comment by dccsillag** [comment]
Actually, just checking, are you on neovim nightly?

**Comment by IndianBoy42** [comment]
Yes I am `NVIM v0.6.0-dev+43-g02bf251bb`


Anshuman Medhi

________________________________

**Comment by dccsillag** [comment]
Could you try it out with the 0.5 release? I'll still do the workaround for people who are on nightly, but I'd like to know whether I massively misunderstood the documentation or if it's a [temporary] bug in neovim.

**Comment by dccsillag** [comment]
Thanks.

**Comment by dccsillag** [comment]
Wait, is that really the _release_ of 0.5? I get

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_
FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict
-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-s
trong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLO
AT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src
/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0
.5.0/build/include
Compiled by builduser
```

**Comment by IndianBoy42** [comment]
Mine should be from runnig this, it was a while ago so I don't know which version of neovim it is. I mainly used my built from source version

```
    sudo add-apt-repository -y ppa:neovim-ppa/unstable
    apt update
    sudo apt install neovim
```

Gimme a few minutes I can try run the 0.5.0 appimage, that should be the easiest way to get a 0.5.0 stable release unintrusively

________________________________

**Comment by dccsillag** [comment]
You can download the binary from here: https://github.com/neovim/neovim/releases/tag/v0.5.0, the `nvim-linux64.tar.gz` file
Then you just need to run the binary, no need to work with appimages

**Comment by IndianBoy42** [comment]
Well the appimage has this version:

```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by ***@***.***
```

Which matches the github releases page (I notice your luajit version is behind)

And the error still happens


Anshuman Medhi

________________________________

**Comment by dccsillag** [comment]
Gotcha.

Thanks for the help!

(I'll take a look into my luajit version issue... thanks for the notice)

**Comment by dccsillag** [comment]
I've just pushed the workaround. Could you confirm that this fixes things?

**Comment by IndianBoy42** [comment]
No more errors. Thanks


Anshuman Medhi

________________________________

**Comment by dccsillag** [comment]
Ah, it appears that this is actually a bug in NeoVim: https://github.com/neovim/neovim/issues/12690

That issue only mentions `<afile>`, but I believe it should also apply to `<abuf>` (which is what we use), given how similar they are.

**Comment by dccsillag** [comment]
After some experimentation, I think it's safe to assume that buffers for which `expand("<abuf>")` is empty during `BufUnload` don't matter to Magma, so the current workaround of ignoring this case is fine. Closing.
