### ISSUE TITLE
Request: persist cell definitions

### ISSUE THREAD

**Issue by tzachar** [dccsillag/magma-nvim#12]
It would be amazing if some way of persisting cell definitions between executions of nvim can be cooked up.

**Comment by dccsillag** [comment]
It definetly can.

I think the best way would be to save outputs in a JSON file. But I'm not sure if the name (+directory?) for this file should be automatic, or if the user should specify a JSON file. The latter is definitely easier, but the former may provide a more seamless UX.

**Comment by dccsillag** [comment]
Actually we can first do the easier one and later do the more complicated one:

First step:
- Have a `:MagmaSave` command which must receive a parameter specifying where to save.
- Have a `:MagmaLoad` command which must receive a parameter specifying where to load from.

Then, later on, we allow these parameters to not receive the parameter, which would make them deduce an automatic file.

This is similar to what was done with `:MagmaInit`, and seems like a good path.

**Comment by tzachar** [comment]
I would suggest mangling the current file name using a template, which the user can change using a config option.

**Comment by dccsillag** [comment]
Yeah I agree. I think an approach like what NeoVim does with `:mkview` and `:loadview` would be best -- maybe we could take a look at that for the second phase.

**Comment by dccsillag** [comment]
First phase done in 9c71d69ab3c804f13ba831f834319a9df404c71a.

**Comment by dccsillag** [comment]
Second phase done in 36aebde8c0e763696b598d2f5fbffd3af483f520.

**Comment by dccsillag** [comment]
Also, everything is documented in the README, and thus this is done. Closing.
