### ISSUE TITLE
Request - Persistent window and cell delimiters

### ISSUE THREAD

**Issue by Lun4m** [dccsillag/magma-nvim#17]
Interesting plugin! I've been using [nvim-ipy](https://github.com/bfredl/nvim-ipy) with the Jupyter QT console for some time, but having everything in one window sounds a lot nicer. 
Anyway back to my requests: 

- Would it be possible to have a persistent output window below the executed cell that doesn't cover the code? Something like in this other [plugin](https://github.com/ahmedkhalf/jupyter-nvim) that reads `.ipynb` files.

- Would it be possible to have manual cell delimeters? Something like:
  ```
  ##
  cell here
  ##
  ```
Edit: Sorry for the mess with the empty issue.

**Comment by dccsillag** [comment]
What exactly does this mean? Isn't this already provided by MagmaSave and MagmaLoad? See https://github.com/dccsillag/magma-nvim/issues/12.

**Comment by Lun4m** [comment]
Sorry for the mess, I updated the initial post!

**Comment by dccsillag** [comment]
These are two different requests, of very different nature; could you separate them into two separate issues? Just for better organization.

**Comment by Lun4m** [comment]
Sure, I'll close this issue and make two new ones. Give me a couple minutes.

**Comment by dccsillag** [comment]
Thanks!
