### ISSUE TITLE
Add GIF demo to README

### ISSUE THREAD

**Issue by dccsillag** [dccsillag/magma-nvim#2]
GIF demos will be added to this issue so that we have an URL to insert in Markdown which does not pollute the repository.

**Comment by dccsillag** [comment]
![demo](https://user-images.githubusercontent.com/15617291/128962596-f422058a-009f-4997-8a52-f7e461be2d36.gif)

**Comment by dccsillag** [comment]
Now with `-loop 0` (i.e., loop indefinetely)

![demo](https://user-images.githubusercontent.com/15617291/128964224-f157022c-25cd-4a60-a0da-7d1462564ae4.gif)

**Comment by wookayin** [comment]
Hello, thanks for the great plugin. Which terminal emulator / GUI did you use to display images on top of nvim window?

**Comment by dccsillag** [comment]
I used st, but any should work. We use [Ueberzug](https://github.com/seebye/ueberzug) to display images.
