### ISSUE TITLE
Error on UpdateRemotePlugins

### ISSUE THREAD

**Issue by JA-Bar** [dccsillag/magma-nvim#3]
First of all, amazing work! I've been hoping for a hydrogen-like plugin for neovim for quite a while now, and this is looking to be a great implementation.

Now to the issue, when running UpdateRemotePlugins the following error is thrown:

``` python
Encountered TypeError loading plugin at /home/user/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma.py: 'type' object is not s
ubscriptable
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/nvim-env/lib/python3.8/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
TypeError: 'type' object is not subscriptable
```

It seems like pynvim isn't recognizing the type annotation syntax from the source file. Removing all indexing from type annotations makes the error go away.

Not sure if this is an error on my end or if it's a common problem.

**Comment by dccsillag** [comment]
Hmmm... which Python version do you have?

**Comment by dccsillag** [comment]
In order to see the stack trace, you can also try running `g:python3_host_prog` (whatever python3 your neovim uses) directly on `rplugin/python3/magma.py`.

**Comment by oponkork** [comment]
I get the same error. I have Python 3.8.10

**Comment by dccsillag** [comment]
You get the same error when running `python3 rplugin/python3/magma.py`?!

**Comment by oponkork** [comment]
This is the output of the above command
```python
Traceback (most recent call last):
  File "/home/oponkork/.local/share/nvim/plugged/magma-nvim/rplugin/python3/magma.py", line 484, in <module>
    class MagmaBuffer:
  File "/home/oponkork/.local/share/nvim/plugged/magma-nvim/rplugin/python3/magma.py", line 495, in MagmaBuffer
    queued_outputs: Queue[Output]
TypeError: 'type' object is not subscriptable

```

**Comment by dccsillag** [comment]
Ah, and now we see the problem.
I have Python 3.9 here, and they might have added proper type annotaions for queue.

I'll solve this, just gimme a sec.

**Comment by dccsillag** [comment]
Should be fixed.

**Comment by oponkork** [comment]
yes, working! Will try the plugin out and possibly leave a feedback.

Thanks a lot.

**Comment by dccsillag** [comment]
You're welcome.
