### ISSUE TITLE
[Bug] Cannot start MagmaInit

### ISSUE THREAD

**Issue by statquant** [dccsillag/magma-nvim#32]
Hello, this is not a bug but I cannot use the plugin at all.
Installation went smoothly and `:checkhealth` appears fine but I simply cannot fire the plugin using `:MagmaInit`, it is like the plugin was not installed.
I am probably doing something very stupid

`:checkhealth`
![image](https://user-images.githubusercontent.com/3612473/146656414-96a2264b-38b0-4229-b976-0ab80ef75747.png)

`:version`
![image](https://user-images.githubusercontent.com/3612473/146656463-ab0d818e-551f-4e9b-bd9e-69c6b0476886.png)

`~/.init.vim` is empty
![image](https://user-images.githubusercontent.com/3612473/146656506-5d35be68-16ea-491e-8199-5429cf6376bf.png)

**Describe the bug**
`E492: Not an editor command: Magma`

**To Reproduce**
Simply type :MagmaInit

**Screenshots**
![image](https://user-images.githubusercontent.com/3612473/146656375-aa6828b8-f680-4538-be55-22288bbe2d78.png)

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser Firefox 95

**Comment by dccsillag** [comment]
Did you run `:UpdateRemotePlugins`?

**Comment by dccsillag** [comment]
If you run `:UpdateRemotePlugins`, it should show something like this:

```
remote/host: python3 host registered plugins ['test.py', 'magma']
remote/host: generated rplugin manifest: /home/daniel/.local/share/nvim/rplugin.vim
```

(Note how it shows that it is registering `magma`.)

**Comment by statquant** [comment]
`Plug` did run it, I did it again manually and see something that makes sense
![image](https://user-images.githubusercontent.com/3612473/146656638-5bdf0ae6-2677-4d84-aef1-bc6b28ebeb77.png)

**Comment by dccsillag** [comment]
Hmm, yeah, that makes sense. And `:MagmaInit` still doesn't work?

**Comment by statquant** [comment]
I'll be damned it now does, I had to get out of tmux though... I'm very sorry for the bother. I am not sure why `Plug` did not execute the hook correctly.

**Comment by dccsillag** [comment]
Phew! Don't worry, it's no bother.

I also have no idea why vim-plug didn't execute that. I'll take a look into it; maybe my installation instructions for it are incorrect.

**Comment by LifeWorks** [comment]
I have the same problem. No MagamaInit command found.

**Comment by LifeWorks** [comment]
OK. Solved. Sorry for the confusion.

**Comment by wjdhamilton** [comment]
I had the same problem. Exiting tmux seemed to be the cure.

**Comment by richardguinness** [comment]
FWIW I found having tmux running made no difference. I experienced the same issue having loaded the plugin with both packer and vim-plug in two separate environments: in both cases running :UpdateRemotePlugins manually was necessary.
