### ISSUE TITLE
[Feature Request] Scrolling pop-up windows or opening them in new buffers

### ISSUE THREAD

**Issue by JulioHC00** [dccsillag/magma-nvim#38]
**Is your feature request related to a problem? Please describe.**
It's sometimes useful to be able to read the whole output from a cell and in that case the limited space that a pop-up offers is not enough.

**Describe the solution you'd like**
Perhaps some way or scrolling the pop-ups or to request opening the output in a new buffer where you can read it and then close it.

**Comment by tzachar** [comment]
See my pull request: #33

**Comment by JulioHC00** [comment]
That's great! Thank!
