### ISSUE TITLE
REQUEST: Add a way to to choose which python interpreter to launch as the kernel

### ISSUE THREAD

**Issue by IndianBoy42** [dccsillag/magma-nvim#4]
Currently it seems to use g.python3_host_prog. Which i feel is okay/good for the plugin itself (I setup a venv for neovim to run plugins inside). But for the kernel it should use the virtual environment activated when python was launched or add a command that chooses which python interpreter to use (similar to vscode)

**Comment by dccsillag** [comment]
I'll take a look at this.

Could you please send your kernelspec for the Python kernel you are starting? To get mine, I did:

```
$ jupyter kernelspec list
[...]
  python3                /home/daniel/.local/share/jupyter/kernels/python3
[...]
```

And then

```
cat /home/daniel/.local/share/jupyter/kernels/python3/kernel.json
```

**Comment by IndianBoy42** [comment]
```
{
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3 (ipykernel)",
 "language": "python",
 "metadata": {
  "debugger": true
 }
}⏎   
```

```
❯ jupyter kernelspec list                                                             
Available kernels:
  python3    /home/amedhi/.local/share/jupyter/kernels/python3
```

There is only one kernel available for me, and there is the kernelspec

If i manually install the virtualenvironments ipython as a kernel then it can work (it will be in the list in MagmaInit). Perhaps a helper for detecting the current virtual environment and installing it as a kernel would be good (i guess this relates to #5)
