### ISSUE TITLE
Install script still refers to "master" branch

### ISSUE THREAD

**Issue by wjdhamilton** [dccsillag/magma-nvim#47]
**Describe the bug**
When attempting to install using vim-plug the following error occurs: 

    fatal: invalid reference: master

**To Reproduce**

Install the plugin per the instructions for vim-plug, i.e.: 

```
Plug 'dccsillag/magma-nvim', { 'do': ':UpdateRemotePlugins' }
```

**Expected behavior**
Vim-plug confirms the plugin installed properly

**Screenshots**
![Screenshot 2022-08-10 at 12 34 44](https://user-images.githubusercontent.com/7499818/183891387-f5ee3434-5250-4b7e-9fff-91510eaaecb1.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.5 
 - Browser: N/A

**Comment by dccsillag** [comment]
There isn't an install script; `:UpdateRemotePlugins` is just a NeoVim command to register remote plugins.

So, as it is, there actually isn't anything referring to the `master` branch specifically there. In fact:

```
magma-nvim  main [~u] $ rg master
magma-nvim  main [~u] ✗ 1 $
```

That is, there is no mention of the `master` branch anywhere in this repo.

I remember experiencing similar issues with vim-plug, though (but with other plugins) -- I don't know why it happens. My workaround was to add a `, branch: 'main'` to the options table:

```
Plug 'dccsillag/magma-nvim', { 'do': ':UpdateRemotePlugins', 'branch': 'main' }
```

**Comment by wjdhamilton** [comment]
Ah! Thank you very much, that fixed it.

Many thanks,

James Hamilton



On 10 Aug 2022, at 13:10, Daniel Csillag ***@***.******@***.***>> wrote:



There isn't an install script; :UpdateRemotePlugins is just a NeoVim command to register remote plugins.

So, as it is, there actually isn't anything referring to the master branch specifically there. In fact:

magma-nvim  main [~u] $ rg master
magma-nvim  main [~u] ✗ 1 $


That is, there is no mention of the master branch anywhere in this repo.

I remember experiencing similar issues with vim-plug, though (but with other plugins) -- I don't know why it happens. My workaround was to add a , branch: 'main' to the options table:

Plug 'dccsillag/magma-nvim', { 'do': ':UpdateRemotePlugins', 'branch': 'main' }

**Comment by wjdhamilton** [comment]
Just looking at that again…what does the “master” in “ magma-nvim  main [~u] $ rg master” refer to?

Many thanks,

James

On 10 Aug 2022, at 20:38, Daniel Csillag ***@***.***> wrote:

﻿

Closed #47<https://github.com/dccsillag/magma-nvim/issues/47> as completed.

**Comment by dccsillag** [comment]
The `magma-nvim  main [~u] $` is my shell's prompt: `magma-nvim` is the directory name, ` main` indicates that I'm on branch main, `[~u]` indicates that there are unstaged files (`u`) and modified files (`~`) (and my `git diff` does not touch anything mentioning any branches, just some internal logic), and `$` is a prompt character separator.

Then, the command `rg master` uses [ripgrep](https://github.com/BurntSushi/ripgrep); think of it as `grep -r master .` but that ignores things in the gitignore, and is overall faster (there are more differences, but that's the gist of it here; it's quite practical). It doesn't give any output, which indicates that there is no file in the repository where the pattern `master` can be found.

**Comment by wjdhamilton** [comment]
I see! Sorry for being thick.

Many thanks,

James Hamilton



On 11 Aug 2022, at 11:35, Daniel Csillag ***@***.******@***.***>> wrote:



The magma-nvim  main [~u] $ is my shell's prompt: magma-nvim is the directory name,  main indicates that I'm on branch main, [~u] indicates that there are unstaged files (u) and modified files (~) (and my git diff does not touch anything mentioning any branches, just some internal logic), and $ is a prompt character separator.

Then, the command rg master uses ripgrep<https://github.com/BurntSushi/ripgrep>; think of it as grep -r master . but that ignores things in the gitignore, and is overall faster (there are more differences, but that's the gist of it here; it's quite practical). It doesn't give any output, which indicates that there is no file in the repository where the pattern master can be found.

**Comment by dccsillag** [comment]
Ah, no worries!
