### ISSUE TITLE
[Bug] MagmaInit fails when Ueberzug is not installed

### ISSUE THREAD

**Issue by augustebaum** [dccsillag/magma-nvim#48]
Thanks very much to the project maintainers, this looks very promising!

Unfortunately I cannot use this as I use MacOS and ueberzug does not work on MacOS (see #15). However, I was wondering if it would be possible to still use magma-nvim without ueberzug, with the caveat that images cannot be displayed?
As it stands, I can't even try out the plugin because `:MagmaInit` complains that ueberzug is not installed.
Or maybe I underestimated how much the project relies on ueberzug?

Thanks in advance for the consideration.

**Comment by dccsillag** [comment]
Oh, that's strange; what you just described (no ueberzug ==> just don't show images) is what's supposed to happen. I'll take a look.

(Ueberzug is not only non-essential to magma-nvim itself, but is reasonably abstracted away in the code.)

**Comment by dccsillag** [comment]
Should be solved now. Can you confirm?

**Comment by augustebaum** [comment]
Confirmed, looking forward to using it! Thanks for the quick feedback.

**Comment by YIPSHINGHIM** [comment]
Hi there,

I seem to be running into a similar issue as the one described here. I'm using a Mac and, as `ueberzug` isn't supported on this platform, I've left that part blank. The results from `:checkhealth` reflect this.

However, I've encountered a snag when trying to run `:MagmaInit`. It's saying that it's not a recognised editor command. 😅

Any help on how to get past this would be greatly appreciated. Thanks in advance for your time and assistance!

<img width="355" alt="CleanShot 2023-06-20 at 00 22 25@2x" src="https://github.com/dccsillag/magma-nvim/assets/75838480/c9b378e5-958a-4721-9b99-ef892984801d">
<br>
<img width="408" alt="CleanShot 2023-06-20 at 00 22 45@2x" src="https://github.com/dccsillag/magma-nvim/assets/75838480/f3913d69-c1ff-47ef-a923-65cbda3597a3">
