### ISSUE TITLE
Can you edit .ipynb files?

### ISSUE THREAD

**Issue by wjdhamilton** [dccsillag/magma-nvim#53]
This seems like a silly question, but how do you get started using this plugin? I had supposed that I would just open a .ipynb file but nvim shows it as an unparsed text file with all the delimiters etc. visible. Are you supposed to start with a blank file and then work from there? 

Sorry if I'm being an idiot!

**Comment by dccsillag** [comment]
This plugin "just" gives you with a handy way of executing code via Jupyter -- it doesn't add support for reading/writing `.ipynb` files.

If you want to edit `.ipynb` files, then I recommend https://github.com/goerz/jupytext.vim.
