### ISSUE TITLE
[Bug] MagmaInit not working

### ISSUE THREAD

**Issue by matheus-ft** [dccsillag/magma-nvim#59]
Magma cannot initialize.

1) Run `:MagmaInit python3`
2) Try to run a block of code
3) Output displays "On Hold"
4) Nothing happens and buffer gets super slow

Apparently Magma never fully initializes, thus it can't run the code. However it does not display any error and slows down the whole buffer. 

I updated my plugins today, after installing Magma on 9-Sep, and I'm using NVIM v0.7.2 on Pop!_OS 22.04.

**Comment by dccsillag** [comment]
Hmm... that sounds like the kernel never sent the 'idle' message (telling that it is done initializing).

Did you have this issue before recently updating the plugin? Moreover, can you start the kernel via a simple `jupyter notebook`, or does that never start as well?

**Comment by matheus-ft** [comment]
No, I didn't have the issue before the update (side note: way to go! Very nice plugin).

And I can start the kernel either via `jupyter notebook` or `jupyter-lab` without issue.

**Comment by matheus-ft** [comment]
Just as an update: I had not tried to use Magma with a virtual environment yet. But I just did and it seems to work fine. The plugin initializes and captures the libraries in the venv, but the problem remains if i just try to initialize the global interpreter.
