### ISSUE TITLE
[Bug] Not an editor commad: MagmaInit python3

### ISSUE THREAD

**Issue by chiawen1** [dccsillag/magma-nvim#62]
![not an editor command ](https://user-images.githubusercontent.com/113413263/191727857-afe9997a-48ab-4f85-80f9-cbce45abf04e.png)
![check heahth](https://user-images.githubusercontent.com/113413263/191727888-a5ff5c3a-60c7-4206-a81a-cfd9e6aa9a5e.png)
I have installed the magma-nvim plugin, but i don't know why it don't have the command MagmaInit, can you help me, thank you!

**Comment by nluetts** [comment]
Hi there!

I have this exact issue, although my `:checkhealth` is fine:

```
magma: health#magma#check
========================================================================
## requirements
   - OK: NeoVim >=0.5
   - OK: Python >=3.8
   - OK: Python package pynvim found
   - OK: Python package jupyter-client found
   - OK: Python package ueberzug found
   - OK: Python package Pillow found
   - OK: Python package cairosvg found
   - OK: Python package pnglatex found
   - OK: Python package plotly found
   - OK: Python package kaleido found
```

@chiawen1 How did you solve the problem?

**Comment by aarimond** [comment]
Hi, I had same issue. 

Might be related to #65 and others. In my case `:UpdateRemotePlugins` did not work. 

I got the commands integrated correctly by upgrading my virtual environment from 3.8 to 3.10 and ran `:UpdateRemotePlugins` manually.
