### ISSUE TITLE
[Bug] UpdateRemotePlugins Failing to Load Python3 Host

### ISSUE THREAD

**Issue by n-sweep** [dccsillag/magma-nvim#65]
**Describe the bug**
`:UpdateRemotePlugins` is failing with `failed to load python3 host` despite a clean `checkhealth`

**To Reproduce**
1. Upon starting neovim, `MagmaInit` is not an editor command.
2. Run `:UpdateRemotePlugins`, receive the following error:

**Error**
```
function remote#host#UpdateRemotePlugins[6]..<SNR>54_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require[12]..provider#Poll, line 7
Vim(if):Error invoking 'poll' on channel 3 (python3-client):^@ch 3 was closed by the client
function remote#host#UpdateRemotePlugins[6]..<SNR>54_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require[12]..provider#Poll, line 17
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
```

**`checkhealth` Output**
```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.10.6
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
```

**Expected behavior**
After a successful `:UpdateRemotePlugins` call, I can use magma-nvim as intended.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Browser: Brave
 - NeoVim Version: 0.9.0-dev

**Additional context**
- If I remove magma-init from my list of plugins, `UpdateRemotePlugins` works as expected.
- Setting `$NVIM_PYTHON_LOG_FILE` has no effect; the file is not populated with any text.
- I was able to successfully install and use magma-nvim inside a WSL instance on Windows 10 before attempting to do the same on this linux machine. Same version of neovim, same settings, etc...

**Comment by TATOAO** [comment]
Experiencing the same issue here, but my error message is different.

<img width="834" alt="Screenshot 2022-11-17 at 23 02 44" src="https://user-images.githubusercontent.com/19830576/202481504-4fb66a45-56b3-4d3a-802c-ce8dfea68ffa.png">

Same with: if removing the $use({ 'dccsillage/maga-nvim', run = ':UpdateRemotePlugins'}) in my plugins magager, UpdateRemotePlugins works just fine.

My system is Ubuntu 20.04, python 3.8.10

**Comment by TATOAO** [comment]
> Experiencing the same issue here, but my error message is different.
> 
> <img alt="Screenshot 2022-11-17 at 23 02 44" width="834" src="https://user-images.githubusercontent.com/19830576/202481504-4fb66a45-56b3-4d3a-802c-ce8dfea68ffa.png">
> 
> Same with: if removing the $use({ 'dccsillage/maga-nvim', run = ':UpdateRemotePlugins'}) in my plugins magager, UpdateRemotePlugins works just fine.
> 
> My system is Ubuntu 20.04, python 3.8.10

I tried to use python3.9 and the no error message popping up

**Comment by WhiteBlackGoose** [comment]
[eca28c6](https://github.com/dccsillag/magma-nvim/commit/eca28c66c38e203316a7eab03340e1618d12fa59) should fix it
