### ISSUE TITLE
[Bug] Cell remains open after executing :MagmaDelete (GIF inside)

### ISSUE THREAD

**Issue by jrnkng** [dccsillag/magma-nvim#68]
Running on a MacBook, whenever I run a cell and hover over the output and then delete the cell I get the following behaviour: https://gyazo.com/5aab9d570bb5d7af391c780a450d5d23. Otherwise the plugin works fantastically and is really cool! Any idea what is going on here?

**Comment by usmcamp0811** [comment]
I'm having the same problem

**Comment by Ch0ronomato** [comment]
same

**Comment by WhiteBlackGoose** [comment]
Should work now
