### ISSUE TITLE
REQUEST: support plotly

### ISSUE THREAD

**Issue by tzachar** [dccsillag/magma-nvim#7]
Is it possible to support plotly figures out of the box? 
The mimetype used is `'application/vnd.plotly.v1+json`

**Comment by dccsillag** [comment]
I'll take a look.

**Comment by dccsillag** [comment]
Things look good on this front -- it looks like the data really is JSON, and Plotly already provides a way to convert it into a PNG image.

I'll probably want to refactor some things before doing this, though. Hope you don't mind.

**Comment by dccsillag** [comment]
I think I did it.

Could you send me some example Plotly code?

**Comment by dccsillag** [comment]
Should be done with commits 97865071255ecf07a2d67790c225d99f8245a6f6, 06c30c88ea508c3745709499efe802de51a1e0a4 and 3e242bc277aa3253d6149d057c8110270d4ff821. Can you confirm?

Note: the first plotly figure may take a little while to show.
