### ISSUE TITLE
Ueberzug is no more maintained

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dccsillag/magma-nvim#72]
First of all, thanks for your amazing work. And thanks to the ueberzug's maintainer, who, unfortunately, recently [burned out](https://github.com/seebye/ueberzug).

As it's not maintaned and not available in pip repositories anymore, we can try to revive it at least to something working.

I [created a fork](https://github.com/WhiteBlackGoose/ueberzug-latest) of it and currently am trying to make it work (I think it even works, but for some reason my plots still don't show up :sweat_smile: ).

I guess we can use this issue as some kind of roadmap who's installing magma and came across this problem.

**Comment by WhiteBlackGoose** [comment]
(just clarification: I'm not a successor of the maintainer or anything (I don't know enough to maintain it). It would be amazing if someone could pick it up though)

**Comment by usmcamp0811** [comment]
I saw that the other day.. that sucks.. I've kind of switched to Kitty.. but do support the effort to have alternatives like ueberzug.. hey does this mean we can change its name? lol cause I can never remember how to spell it when I need to install it :-D

**Comment by sdifru** [comment]
@usmcamp0811 How do you show plots with kitty? I use kitty and am unable to show plots.

**Comment by WhiteBlackGoose** [comment]
@sdifru did you write
```
vim.g.magma_image_provider="kitty"
```
?
