### ISSUE TITLE
Is it possible to evaluate some code from lua?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dccsillag/magma-nvim#74]
Hello. Thanks for this amazing plugin.

I use it occasionally for C# and F#. For them to work smoothly, I need to evaluate two lines of code (to set up correct mimetype). Something like
```
magma = require('magma-nvim')
...
magma.Eval("var a = 5;")
```

Is it possible?

**Comment by usmcamp0811** [comment]
Seems like it is possible.. probably just need to install the kernel.. I found this
https://github.com/tomstitt/lupyter

**Comment by WhiteBlackGoose** [comment]
@usmcamp0811 I already submitted a PR #75 adding it.

**Comment by usmcamp0811** [comment]
damn I completely misread what you were saying.. I thought you were asking if you could evaluate lua code... yea I'm an idiot..

**Comment by WhiteBlackGoose** [comment]
that's np, it seems like I didn't check your link properly either XD
