### ISSUE TITLE
REQUEST: rerun current cell

### ISSUE THREAD

**Issue by tzachar** [dccsillag/magma-nvim#8]
Can we add a command to rerun the current cell the cursor is in?
This would be awesome :)

**Comment by dccsillag** [comment]
Ah, I forgot about that. Don't know how.

Gimme a sec, should be easy.

**Comment by dccsillag** [comment]
Done. See `MagmaReevaluateCell`.

**Comment by tzachar** [comment]
Would be helpful to add to README and keybindings....

**Comment by dccsillag** [comment]
Didn't I do that in `e9925876138007b34b1ce8fc5e34ddac1618ce4d`?

**Comment by tzachar** [comment]
Sorry, just noticed that you did ...
