### ISSUE TITLE
dap does not stop

### ISSUE THREAD

**Issue by jcvillaquira** [dccsillag/magma-nvim#80]
Hi,

hope everyone is doing ok. I am currently configuring my setup in AstroNvim, but I am having a little trouble with the debugger `dap`. I want to debug a big project, and I interact with it via a Notebook but it isn't working for me since magma ignore breakpoints. Thanks, any help will be appreciated.
![image](https://user-images.githubusercontent.com/82904366/208248379-d391ffe6-fded-4283-99ad-db8a1e299439.png)

**Comment by WhiteBlackGoose** [comment]
It's not supposed to work, to be honest.
