### ISSUE TITLE
[Bug] ReevalateCell & Delete cause the output to remain regardless of current cell.

### ISSUE THREAD

**Issue by Riverside96** [dccsillag/magma-nvim#83]
the Delete function does not work but instead leaves the output "stuck"
while the ReevaluateCell does work but again leaves the previous output "stuck"

**Comment by Riverside96** [comment]
Thanks. This could be handy for now. It's a shame as the integration is really nice.

**Comment by WhiteBlackGoose** [comment]
I believe, this is now fixed
