### ISSUE TITLE
[Bug] When I start Magma my neovim starts stuttering

### ISSUE THREAD

**Issue by marcotduenas** [dccsillag/magma-nvim#86]
When I type  MagmaInit my enitre neovim starts to stutter. When I stop Magma, Neovim returns to normal

**Comment by schmidma** [comment]
It seems this timer
https://github.com/dccsillag/magma-nvim/blob/395b48e2e202d82fca76c15d2dcd8785c125d686/rplugin/python3/magma/__init__.py#L56

blocks the entire neovim UI and only if the timer triggers, neovim proceeds with any updates of key presses etc.

**Comment by marcotduenas** [comment]
> Have you been able to solve the problem? I experience the same issue. As soon as calling `MagmaInit` the entire neovim session is nearly unresponsive and stuttering extremely (key input delay of multiple seconds).

I didn't figure out the problem yet, been using emacs last month

**Comment by marcotduenas** [comment]
> It seems this timer
> 
> https://github.com/dccsillag/magma-nvim/blob/395b48e2e202d82fca76c15d2dcd8785c125d686/rplugin/python3/magma/__init__.py#L56
> 
> blocks the entire neovim UI and only if the timer triggers, neovim proceeds with any updates of key presses etc.

Did it resolve for you?

**Comment by schmidma** [comment]
I didn't further investigate the exact packages or dependencies. But after installing some (missing ?) jupyter packages, the stuttering disappeared.
As I said, just guessing, but Magma might be not initializing correctly and retrying? Which causes the delay.

**Comment by marcotduenas** [comment]
> I didn't further investigate the exact packages or dependencies. But after installing some (missing ?) jupyter packages, the stuttering disappeared. As I said, just guessing, but Magma might be not initializing correctly and retrying? Which causes the delay.

Could send me the libraries that you've installed? So I can test in my machine

**Comment by schmidma** [comment]
I think the initial package was `plotly` (installed via dnf on fedora with `python3-plotly`), which of course is not the cause, but any of its dependencies. It might be `python-jupyter-filesystem` which mainly setups the directory structures for other modules. Maybe there is a possibility to get better logging during the initialization phase to track whether any kernel initialization or similar procedures fail.

**Comment by WhiteBlackGoose** [comment]
Does this reproduce on the newest neovim?
