### ISSUE TITLE
Bug: error when trying to show image

### ISSUE THREAD

**Issue by tzachar** [dccsillag/magma-nvim#9]
For the following code:

```python
import numpy as np                                                
import matplotlib.pyplot as plt                                   
                                                                                                                
x = np.random.rand(10000)                                         
plt.hist(x)                                                    
```

I get the following error:
```
Error detected while processing function remote#define#request:                                                                                                       
line    2:                                                                                                                                                            
Error invoking '/home/tzachar/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py:autocmd:CursorMoved:*' on channel 7 (python3-rplugin-host):  
error caught in request handler '/home/tzachar/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py:autocmd:CursorMoved:* []':                  
Traceback (most recent call last):                                                                                                                                    
  File "/home/tzachar/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py", line 47, in inner                                                  
    func(self, *args, **kwargs)                                                                                                                                       
  File "/home/tzachar/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py", line 965, in autocmd_cursormoved                                   
    self._update_interface()                                                                                                                                          
  File "/home/tzachar/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py", line 824, in _update_interface                                     
    magma.update_interface()                                                                                                                                          
  File "/home/tzachar/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py", line 694, in update_interface                                      
    self._show_selected(self.selected_cell)                                                                                                                           
  File "/home/tzachar/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py", line 737, in _show_selected                                        
    self._show_outputs(self.outputs[span], span.end)                                                                                                                  
  File "/home/tzachar/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py", line 611, in _show_outputs                                         
    chunktext = chunk.place(lineno, shape, self.canvas)                                                                                                               
  File "/home/tzachar/.local/share/nvim/site/pack/packer/opt/magma-nvim/rplugin/python3/magma.py", line 264, in place                                                 
    if ((self.img_width/xpixels)/(self.img_height/ypixels))*max_nlines <= w:                                                                                          
ZeroDivisionError: division by zero                                                                                                 
```

**Comment by dccsillag** [comment]
Whoa!

Which terminal emulator are you using?

**Comment by tzachar** [comment]
> Whoa!
> 
> Which terminal emulator are you using?

Kitty

> Also, how did you open neovim? Directly from your shell?
yes.

The following fixes the issue, and I get a proper image:

```diff
diff --git a/rplugin/python3/magma.py b/rplugin/python3/magma.py
index d546f17..7518ad3 100644
--- a/rplugin/python3/magma.py
+++ b/rplugin/python3/magma.py
@@ -259,8 +259,10 @@ class ImageOutputChunk(OutputChunk):
         x, y, w, h = shape
 
         xpixels, ypixels = self._get_char_pixelsize()
+        ypixels = max(1, ypixels)
+        xpixels = max(1, xpixels)
 
-        max_nlines = (h-y)-lineno - 3
+        max_nlines = max((h-y)-lineno - 3, 1)
         if ((self.img_width/xpixels)/(self.img_height/ypixels))*max_nlines <= w:
             nlines = max_nlines
         else:

```

On a side note, the image opened sometime gets attached to a different kitty window, not the one currently displayed.

**Comment by dccsillag** [comment]
That's bizarre. I'll try to debug it.

Your diff seems pretty harmless, and appears to massively alleviate this issue. Would you like me to apply it now, or wait for some debugging on Kitty (in particular, figuring out this 'opens on other window' thing)?

**Comment by tzachar** [comment]
Feel free to apply.

And I really don't know why the image is attaching itself to a different
window.

**Comment by tzachar** [comment]
Seems like I have neglected updating for a while... benn running 0.16.0
Will try to update and report back

**Comment by tzachar** [comment]
ok, updated kitty to the latest version.
makes no difference. Images are still attached to the wrong window.

it has nothing to do with kitty, it also happens when I use gnome-terminal.
The behavior I get is that images are always attached to the *last* instance of the terminal I opened, not the instance I am currently running -- see below, where I have opened two gnome-terminals, the one on the bottom was opened last:

![magma](https://user-images.githubusercontent.com/4946827/129147721-7532a4a1-a6ce-4d19-aaee-903c65d912e8.gif)

**Comment by dccsillag** [comment]
Okay, so the following patch _may_ fix it. Could you check?

```diff
diff --git a/rplugin/python3/magma/utils.py b/rplugin/python3/magma/utils.py
index a01a290..f2f2d3f 100644
--- a/rplugin/python3/magma/utils.py
+++ b/rplugin/python3/magma/utils.py
@@ -1,4 +1,5 @@
 from typing import Union, List, Set, Dict
+import os
 
 from pynvim import Nvim
 import ueberzug.lib.v0 as ueberzug
@@ -58,7 +59,7 @@ class Canvas:
         self._visible.clear()
 
     def add_image(self, path: str, identifier: str, x: int, y: int, width: int, height: int):
-        identifier += f"-{x}-{y}-{width}-{height}"
+        identifier += f"-{os.getpid()}-{x}-{y}-{width}-{height}"
 
         if identifier in self.identifiers:
             img = self.identifiers[identifier]
```

**Comment by tzachar** [comment]
No luck.

Where exactly in the code do you select the window to overlay?

**Comment by tzachar** [comment]
I think its a bug with ueberzug, or the way its used.
When trying the example from https://github.com/seebye/ueberzug#examples, I get the same behavior.
Will open an issue there.

**Comment by dccsillag** [comment]
That lies with Ueberzug.

**Comment by dccsillag** [comment]
Oh yeah, definetly Ueberzug then.

The thing is, its author has disabled issues :/

**Comment by tzachar** [comment]
yeah, just tried to open one....
any way forward?

**Comment by dccsillag** [comment]
At least let him know the issue and ask him where we should submit issues (/ why are issues disabled).

**Comment by dccsillag** [comment]
If Ueberzug starts to be a problem we'll just reimplement the relevant functionality here. But that would be sad.

**Comment by tzachar** [comment]
I don't see any way to contact him. will try through reddit.

**Comment by seebye** [comment]
> That's bizarre. I'll try to debug it, but it's probably a problem in Ueberzug.
> https://github.com/dccsillag/magma-nvim/issues/9#issuecomment-896814108

To the first post and your answer:  
Well I don't see any function of ueberzug in the stacktrace and by looking at it you see that either `(self.img_height/ypixels)` of your code is zero or `ypixels` is zero.  

> possibly with a cleaner API as well  

Ueberzugs api is clean. It is a minimalistic interface which allows you to specify where to display an image on the terminal.  
The python library just offers you the interface necessary to communicate with ueberzug.  
So it is not surprising that depending on your program you may need to write helper classes.  

> https://github.com/dccsillag/magma-nvim/issues/9#issuecomment-897380440  

To explain it roughly (without paying meticulous attention to details):  
If you studied computer science at an university you should know that some problems are undecidable.  
By the theorem of rice this is the case for all semantic properties of a program which are not trivial.  
A property is trivial if all writable programs have this property or none.  
So if you want to make any statement about a semantic property of a program you deal with a undecidable problem.  
Ueberzug needs to deal with a few undecidable problems like which x11 window displays the content of the pseudo tty ueberzug runs in.  
As already explained it is impossible to always make a correct decision. So ueberzug is designed to make a correct decision if the terminal emulator creates only one window per process. This is not the case for the gnome-terminal. For the gnome-terminal every window belongs to the gnome-terminal-server. So the gnome-terminal is not supported. I think it is configurable for kitty whether it should create a process per window or not.  
[I also added it to the wiki of ueberzug](https://github.com/seebye/ueberzug/wiki/Troubleshooting#images-appear-on-the-wrong-terminal-window).  

If you don't want to live with this fact then your only option is to use the protocols of kitty, iterm, ... to display images.  
Ueberzug only helps you to display images on more terminals than the terminals that support showing images,  
but as explained it can not help you to support every terminal emulator which you could create.

**Comment by dccsillag** [comment]
I see. Thank you very much, and sorry for the inconvenience.

> To the first post and your answer:
> Well I don't see any function of ueberzug in the stacktrace and by looking at it you see that either (self.img_height/ypixels) of your code is zero or ypixels is zero or xpixels is zero.

Yeah, that was the case, I admit I skipped some steps there. Though, in my defence, the way we get that `xpixels` and `ypixels` is pretty much the same as Ueberzug does. But it was an issue in Kitty, always saying that it was 0 pixels tall and wide.

> Ueberzugs api is clean. It is a minimalistic interface which allows you to specify where to display an image on the terminal.

And I agree. It's just that after using it here I had some thoughts on things that would have made its usage slightly easier. But nothing concrete, of course.

> > #9 (comment)
> [...]

That makes sense. Thanks for documenting it. Though I disagree on why it should be obvious since I don't remember reading anywhere how Ueberzug detected the current window -- for all I knew that could be some XTerm magic like getting the window size in pixels.

> Ueberzug only helps you to display images on more terminals than the terminals that support showing images,

Absolutely, and that's why we use it. Thanks for creating it!

BTW, we've noticed you disabled issues for Ueberzug and stated you don't accept PRs. If you don't mind me asking, why? Is it no longer properly maintained? Or do you consider it "done?" What's supposed to happen when an actual issue gets found? (Please don't take this badly -- I just think that's important to know as the maintainer of a project which uses your library.)

**Comment by seebye** [comment]
> Though I disagree on why it should be obvious since I don't remember reading anywhere how Ueberzug detected the current window   

I agree it is not documented how ueberzug does this, so it is only obvious if you think about it how this can be implemented.  
I think this is a case of explicit is better than implicit.  

> BTW, we've noticed you disabled issues for Ueberzug  

I disabled them I got the impression that my time is lowly valued.  
E.g. by people who do not care to use the search function or who do not want to read the documentation  
Also I had a case in which someone reported a high memory usage for **large** images which made me spend some hours to debug it just to figure out that there is no memory leak which was also verified by the reporter of the issue.  
He just complained about the memory pillow uses to process these images which is out of my control.  
(In this case the obvious solution would have been to create thumbnails)  

Honestly this stressed me in my exam time, so I disabled them to make it easier to focus on my exams.  

> and stated you don't accept PRs.  

I decided not to accept PRs after following the story/witch hunt of octotree on hacker news and github https://news.ycombinator.com/item?id=24953821.  
Which is about to be summed up that the owner of a AGPLv3 licensed project decided to create a proprietary version of his project and therefore replaced all contributions of third parties by paying a few devs to do a clean room reimplementation.  
As far as I remember most of the work of the project was done by the creator and he only received simple pull requests like adding values to a blacklist.  
So I thought that the whole situation is insane especially as he did a clean room reimplementation.  
I don't plan to do this myself and I don't see a commercial value in ueberzug,  
but this is one of the reasons why I decided not to accept pull requests.  
Just to avoid such crazy people.  

> Or do you consider it "done?"  

Besides one or two small issues I consider it to be done.

**Comment by dccsillag** [comment]
> I disabled them I got the impression that my time is lowly valued.
> [...]

Yeah, that makes sense. Do you intend to turn them back on at a later date? Assuming not, should we ping you if we find something that after some debugging _really_ seems to be an issue with Ueberzug?

> I decided not to accept PRs after following the story/witch hunt of octotree on hacker news and github https://news.ycombinator.com/item?id=24953821.

Interesting. Personally, I think I'll continue accepting PRs, but your decision does make quite some sense.

> Besides one or two small issues I consider it to be done.

That's great to hear!

**Comment by dccsillag** [comment]
Unfortunately that wouldn't really be enough for Magma -- you could have some code running and focus on another window.

**Comment by dccsillag** [comment]
I may have some ideas on how to [mostly] solve this issue, will try them out later. But I'm a bit short on time right now, so don't expect anything today (nor tomorrow, probably).

**Comment by tzachar** [comment]
Well, this is an open sorce project. No one is on a clock.... Your time and responsiveness is greatly appreciated.

Anyway, was searching for alternatives, and came accorss this: [hologram.nvim](https://github.com/edluffy/hologram.nvim). A very interesting project, which solves the issue completely. 

You can then use [this](https://pynvim.readthedocs.io/en/latest/usage/python-plugin-api.html#lua-integration) to easily integrate with the lua code.

**Comment by dccsillag** [comment]
Yeah, but that's just for Kitty (so far), isn't it? And, in particular, it doesn't seem like they have any plans for supporting something like Ueberzug.

We can look into making some form of "image providers", though, where hologram would be one, and Ueberzug another.

**Comment by tzachar** [comment]
There are plans to support the image protocol of iterm2, which would cover all currently available options.
I think that ueberzug should be used as a fallback if no native option exists.

**Comment by dccsillag** [comment]
Okay. Let's move this into a new issue regarding implementation of other image display methods, so that we don't needlessly bother @seebye.

I've mostly setup an infrastructure for image providers in c31b19efd5533d33a275c604f04736118b6c3a2e; we'd still need to work on [this bit of code](https://github.com/dccsillag/magma-nvim/blob/c31b19efd5533d33a275c604f04736118b6c3a2e/rplugin/python3/magma/outputchunks.py#L75-L93), though.

**Comment by tzachar** [comment]
Ok, will open a new issue.

One last thing; the code [here](https://github.com/dccsillag/magma-nvim/blob/c31b19efd5533d33a275c604f04736118b6c3a2e/rplugin/python3/magma/outputchunks.py#L75-L93) will not usually work, see https://man7.org/linux/man-pages/man4/tty_ioctl.4.html. The ws_xpixel and ws_ypixel are not guranteed to be reurned.
