### ISSUE TITLE
[Feature Request] Enhance documentation for Plug 

### ISSUE THREAD

**Issue by mkonig** [dccsillag/magma-nvim#91]
**Is your feature request related to a problem? Please describe.**
Related to issue #47 
And maybe some other closed issues about commands not showing up. 
Magma commands did not show up when using the Plug example line in the README.md

**Describe the solution you'd like**
Please add 
Plug 'dccsillag/magma-nvim', { 'do': ':UpdateRemotePlugins', 'branch': 'main' }
to the documentation.
I had to add 'branch': 'main' to make the Magma commands show up in nvim.

**Comment by WhiteBlackGoose** [comment]
Main is the default branch. It should not require specifying it explicitly. Maybe it's because :UpdateRemotePlugin wasn't called at a certain moment, so when you specified the branch it re-ran it again?

**Comment by mkonig** [comment]
I switched to lazy and it work now without specifying the branch.
{ 'WhiteBlackGoose/magma-nvim-goose', build = ':UpdateRemotePlugins' },

**Comment by WhiteBlackGoose** [comment]
@mkonig make sure to use this plugin, not my fork, as the fork is now deprecated as I curate this plugin now
